version: '3'

volumes:
    nwvol:
    
networks:
    nwnet:
    
services:
    nwdb:
        image: zhichao/nwdb:v1
        build:
            context: ./database
        environment:
        - MYSQL_ROOT_PASSWORD=changeit
        - COMPOSE_TLS_VERSION=TLSv1_2
        networks:
        - nwnet
        volumes:
        - nwvol:/var/lib/mysql
        
    nwapp:
        image: zhichao/nwapp:v1
        build:
            context: ./server
        environment:
        - DB_HOST=nwdb
        - DB_PORT=3306
        - DB_USER=root
        - DB_PASSWORD=changeit
        - COMPOSE_TLS_VERSION=TLSv1_2
        networks:
        - nwnet
        ports:
        - 80:3000
        
        