---
apiVersion: v1
kind: ConfigMap
metadata:
    name: weather-configmap
    labels:
        name: weather-configmap
        
data:
    APP_DEFAULT_CITY: singapore
    
---
apiVersion: v1
kind: Secret
metadata:
    name: weather-secret
    labels:
        name: weather 
        
data:
    APP_ID: MzE5YTg2YzAxMzE0N2NlYzQ4OGY1ZDFhYmNjNWNiYzk=
        
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: weather-deploy
    namespace: default
    labels:
        name: weather
        version: 'v1'

spec:
    replicas: 4
    selector:
        matchLabels:
            name: weather-pod
    template:
        metadata: 
            name: weather-pod
            labels:
                name: weather-pod
        spec:
            containers:
            - name: weather-container
              image: stackupiss/weather:v1
              imagePullPolicy: Always
              ports:
              - name: weather-http
                containerPort: 3000
              envFrom:
              - configMapRef:
                    name: weather-configmap
              - secretRef:
                    name: weather-secret
                        
---
apiVersion: v1
kind: Service
metadata:
    name: weather-service
    labels:
        name: weather-service

spec:
    type: LoadBalancer
    selector:
        name: weather-pod
    ports:
    - name: http
      port: 80
      targetPort: weather-http