---
apiVersion: v1
kind: ConfigMap
metadata:
    name: myapp-configmap
    namespace: myns
    labels:
        name: myapp-configmap
data:
    DB_USER: root
    DB_HOST: mydb-svc.myns.svc.cluster.local
    DB_PORT: "3306"
    
---
apiVersion: v1
kind: Secret
metadata:
    name: myapp-secret
    namespace: myns
    labels:
        name: myapp-secret 
data:
    DB_PASSWORD: Y2hhbmdlaXQ=
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: myapp-deploy
    namespace: myns
    labels:
        name: myapp
        version: 'v1'

spec:
    replicas: 3
    minReadySeconds: 5
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 0
    selector:
        matchLabels:
            name: myapp-pod
    template:
        metadata: 
            name: myapp-pod
            namespace: myns
            labels:
                name: myapp-pod
        spec:
            containers:
            - name: myapp-container
              image: stackupiss/northwind-app:v1
              imagePullPolicy: Always
              env:
              - name: INSTANCE_IP_ADDRESS
                valueFrom:
                    fieldRef: 
                        fieldPath: status.podIP
              envFrom:
              - configMapRef:
                    name: myapp-configmap
              - secretRef:
                    name: myapp-secret
              ports:
              - name: myapp-http
                containerPort: 3000
                
---
apiVersion: v1
kind: Service
metadata:
    name: myapp-svc
    namespace: myns
    labels:
        name: myapp-svc

spec:
    type: LoadBalancer
    selector:
        name: myapp-pod
    ports:
    - name: http
      port: 80
      targetPort: myapp-http