apiVersion: apps/v1
kind: Deployment
metadata:
    name: myappv1-deployment
    labels:
        name: myappv1
        
spec:
    replicas: 1
    selector:
        matchLabels:
            app: myappv1
    template:
        metadata:
            labels:
                app: myappv1
        spec:
            containers:
            - image: stackupiss/northwind-app:v1
              name: mydb
              env:
              - name: DB_USER
                value: root
              - name: DB_PASSWORD
                value: changeit
              - name: DB_HOST
                value: mydb-svc.default.svc.cluster.local
              - name: DB_PORT
                value: "3306"
              ports:
              - containerPort: 3000
                name: myappv1
              imagePullPolicy: Always